name: "publish docs"

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12.3'
      
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Build Pelican
        run: pelican 
      
      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "output/"